services:
  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=newroot
      - DB_NAME=food_delivery
    restart: unless-stopped
    networks:
      - app-network

  mysql-db:
    image: mysql:8.0.14
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=newroot
      - MYSQL_DATABASE=food_delivery
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: