version: "3.9"
services:
  db:
    image: mysql:8
    restart: always
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: food_delivery
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: .
    container_name: nest-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: food_delivery
      JWT_SECRET: JWT_SECRET
    command: ["npm", "run", "start:prod"]

volumes:
  db-data:
